### ISSUE TITLE
Eggs

### ISSUE THREAD

**Issue by maximousblk** [nestdotland/roadmap#3]
## Eggs

The go-to dev tool for Deno module devs.

- Avoid using `--unstable` APIs
- CLI only
- Use `/.well-known/deno-import-intellisense.json` to get modules
- Support semver constraints (similar to [udd](https://github.com/hayd/deno-udd))
- Commands
  - `add` - add module
  - `update` - update module
  - `cache` - cache all dependencies
  - `run` - script runner
  - `check` - type check all files
  - `lint` - lint all files
  - `fmt` - check formatting for all files
  - suggest more...

#### Configuration

```yml
# ./.eggs.yml

# local deno installed to `./.eggs/deno`
deno: 1.12

lock_file: ./mod.lock.json
import_map: ./modules.json

# for deps management
dependencies: ./deps.ts
# or
dependencies:
  - ./deps.ts
  - ./dev-deps.ts

registries:
  - nest.land
  - deno.land

deno:
  compilerOptions:
    strict: true

  lint:
    rules:
      tags: ["recommended"]

env:
  PORT: 3000
# or
env: ./.env.local

# what shell to run commands in
shell: bash

# eggs run <script>
scripts:
  start: deno run --allow-net server.ts
  test: deno test --allow-net server_test.ts
  fmt: deno fmt --ignore="node_modues"

# tools will be installed to `./.eggs/tools/`
tools:
  - name: nest
    src: https://nest.land/-/nest@1.0.0/nest.ts
    location: https://nest.land
    allow:
      read: ./
      net: ['gql.nest.land']
      run: ['deno']
      # ...

hooks:
  pre_commit: deno fmt --check --ignore="node_modues"
```

#### Commands

```sh
eggs # setup the project environment (cache dependencies, setup git hooks, etc)

eggs cache # caches all (public/private) dependencies

eggs add [...modules | url to file] # add export to the deps file

eggs update [options] [ <target_file> or deps.ts ] # bump all the modules to the specified limit
    Options:
        -r, --registry         name of the registry to lookup

eggs remove [options] [ <target_file> or deps.ts ] [modules] # removes export from the target file

eggs purge [options] [ <target_file> or deps.ts ] # analyse and remove unused deps
    Options:
        -m, --map              use an import map instead

eggs upgrade # update eggs to the latest version
```

## Notes

- `hatcher` should be merged into `eggs`, though still be usable as a module.

> Why are Nest CLI and eggs separate?

Nest CLI is the main cli you would use to create and publish modules. Eggs is a set of dev tools like script runner, module manager, etc.
